Upgrade to kehaar 0.8.1
democracyworks/kraken-http-api-lein-template pull request #8
Opened 2017-01-11 17:04 UTC by tie-rack

2017-01-11 18:17 UTC, cap10morgan requested changes

2017-01-11 18:17 UTC, cap10morgan commented on resources/leiningen/new/kraken_http_api/channels.clj
> +  (doseq [c []]
Should we add a comment here about what this is for and that it should be removed if you don't end up needing it?

2017-01-11 18:17 UTC, cap10morgan commented on resources/leiningen/new/kraken_http_api/project.clj
>                   [io.pedestal/pedestal.service-tools "0.4.1"]
Can we update the rest of the deps (that don't require other changes) while we're in here? Fine if you want to do it in another PR.

2017-01-11 20:09 UTC, tie-rack commented on resources/leiningen/new/kraken_http_api/channels.clj
> +  (doseq [c []]
Good idea.

2017-01-11 20:10 UTC, tie-rack commented on resources/leiningen/new/kraken_http_api/project.clj
>                   [io.pedestal/pedestal.service-tools "0.4.1"]
I vote to do it in another PR.

2017-02-06 22:21 UTC, cap10morgan commented on resources/leiningen/new/kraken_http_api/project.clj
>                   [io.pedestal/pedestal.service-tools "0.4.1"]
OK, let's see that PR then! :)

2017-02-06 22:21 UTC, cap10morgan approved these changes

2017-02-14 21:47 UTC, cap10morgan commented
@tie-rack Do you want to merge this, do a new one for kehaar 0.10.1, and a third one for updating the other deps? Or something else?

2017-02-14 21:49 UTC, tie-rack commented
@cap10morgan I'll update kehaar to 0.10.1 in this PR and make one for dep updates.

2017-02-14 21:50 UTC, cap10morgan commented
@tie-rack Can you do the same for the `-works` one too?

2017-04-25 15:37 UTC, cap10morgan commented
@tie-rack What should we do with this guy?

2017-04-25 15:38 UTC, tie-rack commented
@cap10morgan even this is behind the times now, isn't it? Let's close and make a story to update these templates more generally. Sound okay?

2017-04-25 15:42 UTC, cap10morgan commented
👍

2017-04-25 15:42 UTC, closed without merging