Spring cleaning
democracyworks/kraken-http-api-lein-template pull request #9
Opened 2017-05-16 17:28 UTC by tie-rack

* YourKit!
* Newrelic!
* Uberjar!
* Dependency version updates!
* Cleanup!

2017-05-16 21:15 UTC, cap10morgan commented on resources/leiningen/new/kraken_http_api/PROJECT@.service.template
> +  --env RABBITMQ_PORT_5672_TCP_ADDR=$(curl -s http://${COREOS_PRIVATE_IPV4}:8500/v1/kv/rabbitmq/host?raw) \
Hmm, yeah, now that I think about it, we probably want this in the `-works` template too.

2017-05-16 21:19 UTC, cap10morgan requested changes

2017-05-16 21:19 UTC, cap10morgan commented on resources/leiningen/new/kraken_http_api/docker-compose.yml
>    image: rabbitmq:3.5.3-management
This should be bumped up to `rabbitmq:3.6.9-management` now.

2017-05-16 21:19 UTC, cap10morgan commented on resources/leiningen/new/kraken_http_api/server.clj
> +    (start-http-server)
What's the motivation for this change?

2017-05-16 21:23 UTC, tie-rack commented on resources/leiningen/new/kraken_http_api/server.clj
> +    (start-http-server)
I was using user-http-api as my guide and it doesn't pass that arg. All the rest do, though. I'll revert that.

2017-05-16 21:30 UTC, cap10morgan commented on resources/leiningen/new/kraken_http_api/Dockerfile
> +    -javaagent:resources/jars/com.newrelic.agent.java/newrelic-agent.jar \
Maybe we should get the cgroup heap stuff in here too? And in the works template?

2017-05-17 14:39 UTC, tie-rack commented on resources/leiningen/new/kraken_http_api/PROJECT@.service.template
> +  --env RABBITMQ_PORT_5672_TCP_ADDR=$(curl -s http://${COREOS_PRIVATE_IPV4}:8500/v1/kv/rabbitmq/host?raw) \
I'll open a new PR for the -works template today.

2017-05-17 14:39 UTC, tie-rack commented on resources/leiningen/new/kraken_http_api/Dockerfile
> +    -javaagent:resources/jars/com.newrelic.agent.java/newrelic-agent.jar \
Yep. Update soon.

2017-05-17 16:22 UTC, cap10morgan approved these changes
🐞

2017-05-17 17:27 UTC, merged